# Generated by Django 5.1.1 on 2024-09-13 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='enployeeDetails',
            new_name='employeeDetails',
        ),
    ]
